#cloud-config
package_update: false
package_upgrade: false
output: { all: "| tee -a /var/log/cloud-init-output.log" }
final_message: "The system is finally up, after $UPTIME seconds"
#packages:
#  - ipa-server
#  - bind-dyndb-ldap
runcmd:
  - [sh, -lc, "dnf update -y"]
  - [sh, -lc, "dnf install ipa-server bind-dyndb-ldap -y"]
  - [
      sh,
      -lc,
      "GW_IP=$(ip route show default | awk '/default/ {print $3; exit}'); if [ -n \"$GW_IP\" ]; then echo \"Found gateway IP: $GW_IP. Configuring systemd-resolved.\"; mkdir -p /etc/systemd/resolved.conf.d; printf '%s\\n' '[Resolve]' > /etc/systemd/resolved.conf.d/99-gateway-dns.conf; printf 'DNS=%s\\n' \"$GW_IP\" >> /etc/systemd/resolved.conf.d/99-gateway-dns.conf; systemctl restart systemd-resolved; echo \"DNS configuration updated successfully.\"; else echo \"Warning: Could not determine default gateway IP. DNS not configured.\"; fi",
    ]
  - [
      sh,
      -lc,
      "firewall-cmd --permanent --add-service={http,https,dns,freeipa-ldap,freeipa-ldaps,kerberos,kpasswd,ntp}",
    ]
  - [sh, -lc, "firewall-cmd --reload"]
