#cloud-config
package_update: true
package_upgrade: true
packages:
  - ipa-server
  - bind-dyndb-ldap
runcmd:
  - [
      sh,
      -lc,
      "firewall-cmd --permanent --add-service={http,https,dns,freeipa-ldap,freeipa-ldaps,kerberos,kpasswd,ntp}",
    ]
  - [sh, -lc, "firewall-cmd --reload"]
