#cloud-config
package_update: false
package_upgrade: false
output: { all: "| tee -a /var/log/cloud-init-output.log" }
final_message: "The system is finally up, after $UPTIME seconds"
#packages:
#  - ipa-server
#  - bind-dyndb-ldap
runcmd:
  - [sh, -lc, "dnf update -y"]
  - [sh, -lc, "dnf install ipa-server bind-dyndb-ldap -y"]
  - [
      sh,
      -lc,
      "firewall-cmd --permanent --add-service={http,https,dns,freeipa-ldap,freeipa-ldaps,kerberos,kpasswd,ntp}",
    ]
  - [sh, -lc, "firewall-cmd --reload"]
